version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8585:80'
        volumes:
            - ./src:/var/www/html

    db:
        image: 'mariadb'
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: blog
            MYSQL_USER: nolan
            MYSQL_PASSWORD: nolan
            MYSQL_ROOT_PASSWORD: root
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    phpmyadmin:
        image: phpmyadmin
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
volumes:
    persistent: